version: '3.8'
services:
  web:
    build: .
    ports:
      - "443:443"
    depends_on:
      - elasticsearch
    volumes:
      - ./app.py:/app.py
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
      - web-logs:/var/log/nginx

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.3
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - web-logs:/var/log/nginx:ro
    command: ["filebeat", "-e", "-strict.perms=false"]
    depends_on:
      - elasticsearch

volumes:
  esdata:
  web-logs: